name: Terraform CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4          # Get your code
      - uses: hashicorp/setup-terraform@v3 # Install Terraform
      - run: terraform fmt -check          # Ensure formatting is clean
      - run: terraform init -backend=false # Install plugins (no remote backend needed)
      - run: terraform validate            # Sanity check
      - name: Terraform Plan (dry-run)
        run: terraform plan -lock=false -input=false
